services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  etl_app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: myuser
      DB_PASS: mypassword
      DB_NAME: mydb
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./config:/app/config

volumes:
  pgdata:
