version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:2.7.1
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: ${AIRFLOW__CORE__SQL_ALCHEMY_CONN}
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./dags:/opt/airflow/dags:cached
      - ./logs:/opt/airflow/logs:cached
      - ./plugins:/opt/airflow/plugins:cached

  etl-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      DB_HOST: postgres
      DB_USER: myuser
      DB_PASS: mypassword
      DB_NAME: mydb
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - airflow
    volumes:
      - ./config:/app/config

volumes:
  pgdata:
