dbt_project:
  outputs:
    dev:
      dbname: mydb
      host: localhost
      pass: mypassword
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: myuser
  target: dev
