apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: airflow
  name: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: airflow
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s/
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: airflow
    spec:
      containers:
        - name: airflow
          image: apache/airflow:2.7.1
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: LocalExecutor
            - name: AIRFLOW__CORE__FERNET_KEY
              value: replace_with_secure_fernet_key
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              value: postgresql+psycopg2://myuser:mypassword@postgres:5432/mydb
          volumeMounts:
            - mountPath: /opt/airflow/dags
              name: airflow-claim0
            - mountPath: /opt/airflow/logs
              name: airflow-logs-pvc    # updated to use airflow-logs-pvc here
            - mountPath: /opt/airflow/plugins
              name: airflow-claim2
      restartPolicy: Always
      volumes:
        - name: airflow-claim0
          persistentVolumeClaim:
            claimName: airflow-claim0
        - name: airflow-logs-pvc
          persistentVolumeClaim:
            claimName: airflow-logs-pvc
        - name: airflow-claim2
          persistentVolumeClaim:
            claimName: airflow-claim2
