apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: etl-app
  name: etl-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: etl-app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s/
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: etl-app
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: postgres
            - name: DB_NAME
              value: mydb
            - name: DB_PASS
              value: mypassword
            - name: DB_USER
              value: myuser
          image: etl-app
          imagePullPolicy: IfNotPresent
          name: etl-app
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: /app/config
              name: etl-app-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: etl-app-cm0
          name: etl-app-cm0
